# Bootstrap the storageConfigurator, which will create storageClasses as defined in globalValues.yaml.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageconfigurator
  namespace: argocd
spec:
  project: argocd-scale
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  source:
    repoURL: https://github.com/FE-JT/argocd-manifests.git
    targetRevision: main
    path: storageConfigurator
    helm:
      valueFiles:
        - values.yaml
        - ../globalValues.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
