apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.{{ .Values.global.domain }}`)
      # middlewares:
      #   - name: dashboard-auth
      priority: 10
      services:
        - kind: TraefikService
          name: api@internal
  tls:
    secretName: traefik-tls
