apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
spec:
  # Secret names are always required.
  secretName: traefik-tls
  revisionHistoryLimit: 1
  dnsNames:
    - traefik.{{ .Values.global.domain }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer