# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
# domain names are overridden due to derivation from Values.global.domain
argo-cd: 
  configs:
    params:
      # traefik terminates TLS at edge
      server.insecure: true
    cm:
      url: 'https://argocd.xwcs.io'

  server:
    certificate:
      domain: argocd.xwcs.io
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/revision-history-limit: '1'
      tls: true
      hostname: argocd.xwcs.io

  notifications:
    argocdUrl: 'https://argocd.xwcs.io'
  
  applicationSet:
    certificate:
      domain: argocd.xwcs.io